import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './hooks/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '16px',
    },
    extend: {
      fontFamily: {
        sans: ['var(--font-inter-display)', 'Inter Display', 'sans-serif'],
      },
      colors: {
        grey: {
          900: 'var(--color-grey-900)',
          800: 'var(--color-grey-800)',
          700: 'var(--color-grey-700)',
          600: 'var(--color-grey-600)',
          500: 'var(--color-grey-500)',
          400: 'var(--color-grey-400)',
          300: 'var(--color-grey-300)',
          200: 'var(--color-grey-200)',
          100: 'var(--color-grey-100)',
          50: 'var(--color-grey-50)',
          25: 'var(--color-grey-25)',
        },
        blue: {
          900: 'var(--color-blue-900)',
          800: 'var(--color-blue-800)',
          700: 'var(--color-blue-700)',
          600: 'var(--color-blue-600)',
          500: 'var(--color-blue-500)',
          400: 'var(--color-blue-400)',
          300: 'var(--color-blue-300)',
          200: 'var(--color-blue-200)',
          100: 'var(--color-blue-100)',
          50: 'var(--color-blue-50)',
        },
        green: {
          900: 'var(--color-green-900)',
          800: 'var(--color-green-800)',
          700: 'var(--color-green-700)',
          600: 'var(--color-green-600)',
          500: 'var(--color-green-500)',
          400: 'var(--color-green-400)',
          300: 'var(--color-green-300)',
          200: 'var(--color-green-200)',
          100: 'var(--color-green-100)',
          50: 'var(--color-green-50)',
        },
        red: {
          900: 'var(--color-red-900)',
          800: 'var(--color-red-800)',
          700: 'var(--color-red-700)',
          600: 'var(--color-red-600)',
          500: 'var(--color-red-500)',
          400: 'var(--color-red-400)',
          300: 'var(--color-red-300)',
          200: 'var(--color-red-200)',
          100: 'var(--color-red-100)',
          50: 'var(--color-red-50)',
        },
        yellow: {
          900: 'var(--color-yellow-900)',
          800: 'var(--color-yellow-800)',
          700: 'var(--color-yellow-700)',
          600: 'var(--color-yellow-600)',
          500: 'var(--color-yellow-500)',
          400: 'var(--color-yellow-400)',
          300: 'var(--color-yellow-300)',
          200: 'var(--color-yellow-200)',
          100: 'var(--color-yellow-100)',
          50: 'var(--color-yellow-50)',
        },
        violet: {
          900: 'var(--color-violet-900)',
          800: 'var(--color-violet-800)',
          700: 'var(--color-violet-700)',
          600: 'var(--color-violet-600)',
          500: 'var(--color-violet-500)',
          400: 'var(--color-violet-400)',
          300: 'var(--color-violet-300)',
          200: 'var(--color-violet-200)',
          100: 'var(--color-violet-100)',
          50: 'var(--color-violet-50)',
        },
        orange: {
          900: 'var(--color-orange-900)',
          800: 'var(--color-orange-800)',
          700: 'var(--color-orange-700)',
          600: 'var(--color-orange-600)',
          500: 'var(--color-orange-500)',
          400: 'var(--color-orange-400)',
          300: 'var(--color-orange-300)',
          200: 'var(--color-orange-200)',
          100: 'var(--color-orange-100)',
          50: 'var(--color-orange-50)',
        },
        border: 'var(--color-grey-100)',
        input: 'var(--color-grey-100)',
        ring: 'var(--color-blue-500)',
        background: 'var(--bg-primary)',
        foreground: 'var(--text-primary)',
        primary: {
          DEFAULT: 'var(--color-blue-500)',
          foreground: '#FFFFFF',
        },
        secondary: {
          DEFAULT: 'var(--color-grey-50)',
          foreground: 'var(--text-primary)',
        },
        destructive: {
          DEFAULT: 'var(--color-red-500)',
          foreground: '#FFFFFF',
        },
        muted: {
          DEFAULT: 'var(--color-grey-25)',
          foreground: 'var(--text-secondary)',
        },
        accent: {
          DEFAULT: 'var(--color-grey-50)',
          foreground: 'var(--text-primary)',
        },
        popover: {
          DEFAULT: '#FFFFFF',
          foreground: 'var(--text-primary)',
        },
        card: {
          DEFAULT: '#FFFFFF',
          foreground: 'var(--text-primary)',
        },
        success: 'var(--color-green-500)',
        warning: 'var(--color-yellow-500)',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '24': '96px',
        '28': '112px',
      },
      borderRadius: {
        sm: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
      },
      fontSize: {
        h1: ['48px', { lineHeight: '56px', fontWeight: '700' }],
        h2: ['36px', { lineHeight: '44px', fontWeight: '700' }],
        h3: ['30px', { lineHeight: '38px', fontWeight: '600' }],
        h4: ['28px', { lineHeight: '36px', fontWeight: '600' }],
        h5: ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
      },
      transitionDuration: {
        micro: '100ms',
        popover: '150ms',
        modal: '200ms',
        page: '250ms',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
export default config
