export const TERM_GLOSSARY: Record<string, string> = {
  Parties: 'The individuals or companies entering into this agreement.',
  'Effective Date': 'The date the agreement starts being legally binding.',
  'Confidentiality Obligations': 'What each party must keep secret and for how long.',
  'Permitted Disclosures': 'Situations where sharing confidential information is allowed (e.g. legal requirement).',
  'Term & Duration': 'How long the agreement lasts before it expires.',
  'Governing Law': "Which country or state's laws apply if there's a dispute.",
  Jurisdiction: 'Which court system handles any legal dispute.',
  'IP Ownership': 'Who owns any ideas, inventions, or content created under the agreement.',
  'Non-Solicitation': "Restrictions on hiring each other's employees or clients.",
  'Breach & Remedy': 'What happens if either party breaks the agreement, and how it can be fixed.',
  'Service Scope': 'Exactly what work or services are being provided.',
  'Payment Terms': 'How much is paid, when, and by what method.',
  'Invoice Schedule': 'How often invoices are sent and payment is expected.',
  'Late Payment Penalty': 'Extra fees charged if payment is late.',
  'Liability Cap': 'The maximum amount one party can be required to pay the other if something goes wrong.',
  Indemnification: 'Who pays for damages if something goes wrong.',
  'Termination Clause': 'How and when either party can end the agreement early.',
  'Dispute Resolution': 'The agreed process for resolving disagreements (e.g. mediation, arbitration, court).',
  'Notice Period': 'How much advance warning is required before ending the agreement.',
}
